# Generated by Django 5.0.7 on 2024-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capturedevent',
            old_name='event_name',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='capturedevent',
            old_name='event_date_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='capturedevent',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='capturedevent',
            name='source_text',
        ),
        migrations.AddField(
            model_name='capturedevent',
            name='name',
            field=models.CharField(default='Event name here', max_length=255),
        ),
    ]
